// entry for the `blog-types` package. two halves are blog's build output:
//   types.ts   — generated by `sanity typegen` (result types + @sanity/client overload)
//   queries.ts — the groq query consts, copied verbatim from blog/queries.ts
// project.ts is hand-authored shared project coordinates (id/dataset).
// platform imports result types, query strings, AND project coords from here,
// and never from blog.

export * from "./project";
export * from "./queries";
export * from "./types";
