import type { IToken } from "../types";

export const custom_tokens: IToken[] = [
  {
    id: "alc_1_karate",
    code: "KARATE-1",
    symbol: "KARATE",
    name: "Karate",
    precision: 18,
    logo: "/icons/currencies/karate.png",
    network: "eth",
    color: "#000",
    cg_id: "karate-combat",
  },
  {
    id: "man_295_karate",
    code: "KARATE-295",
    symbol: "KARATE",
    name: "Karate",
    precision: 18,
    logo: "/icons/currencies/karate.png",
    network: "hbar",
    color: "#000",
    cg_id: "karate-combat",
  },
  {
    id: "alc_1_reef",
    code: "REEF-1",
    symbol: "REEF",
    name: "Reef",
    precision: 18,
    logo: "/icons/currencies/reef.png",
    network: "eth",
    color: "#000",
    cg_id: "reef",
  },
  {
    id: "alc_56_reef",
    code: "REEF-56",
    symbol: "REEF",
    name: "Reef",
    precision: 18,
    logo: "/icons/currencies/reef.png",
    network: "bnb",
    color: "#f0b90a",
    cg_id: "reef",
  },
  // https://docs.reef.io/docs/developers/networks/#mainnet-info-sheet
  {
    id: "man_13939_reef",
    code: "REEF-13939",
    symbol: "REEF",
    name: "Reef",
    precision: 18,
    logo: "/icons/currencies/reef.png",
    network: "reef",
    color: "#6B46C1",
    cg_id: "reef",
  },
];
